include:
  - 'gitlab-ci-template.yml'

stages:
  - 📦 Build Image
  - 📦 Production Image

Gitlab CI:
  extends: .build-base
  stage: 📦 Build Image
  variables:
    DOCKER_IMAGE: 'jetx'
    DOCKER_TAG: 'gitlab-ci'
    DOCKER_FILE: 'Dockerfile_ci'
    DOCKER_BUILD_ARGS: '--build-arg PRODUCTION_IP=$PRODUCTION_IP --build-arg STAGING_IP=$STAGING_IP'
  when: manual

Node 18:
  extends: .build-base
  stage: 📦 Build Image
  variables:
    DOCKER_IMAGE: 'node'
    DOCKER_TAG: '18'
    DOCKER_FILE: 'Dockerfile_node'
    DOCKER_BUILD_ARGS: '--build-arg NODE_BASE_IMAGE=18-alpine'
    PLATFORM: 'linux/amd64,linux/arm64/v8'
  when: manual

PHP cli:
  extends: .build-base
  stage: 📦 Build Image
  variables:
    DOCKER_IMAGE: 'php'
    DOCKER_TAG: 'cli-v8'
    DOCKER_FILE: 'Dockerfile_php'
    DOCKER_BUILD_ARGS: '--build-arg PHP_IMAGE=8.2-cli-alpine'
  when: manual

PHP fpm pg:
  extends: .build-base
  stage: 📦 Production Image
  variables:
    DOCKER_IMAGE: 'php'
    DOCKER_TAG: 'fpm-v8-pg'
    DOCKER_FILE: 'Dockerfile_php'
    DOCKER_BUILD_ARGS: '--build-arg PHP_IMAGE=8.2-fpm-alpine --build-arg DB_EXT=pdo_pgsql --build-arg DB_EXT_LIB=postgresql-dev'
    PLATFORM: 'linux/amd64,linux/arm64/v8'
  when: manual

PHP fpm mysql:
  extends: .build-base
  stage: 📦 Production Image
  variables:
    DOCKER_IMAGE: 'php'
    DOCKER_TAG: 'fpm-v8-pdo'
    DOCKER_FILE: 'Dockerfile_php'
    DOCKER_BUILD_ARGS: '--build-arg PHP_IMAGE=8.2-fpm-alpine --build-arg DB_EXT=pdo_mysql'
    PLATFORM: 'linux/amd64,linux/arm64/v8'
  when: manual

# Install mysqli for wordpress project
PHP fpm mysqli:
  extends: .build-base
  stage: 📦 Production Image
  variables:
    DOCKER_IMAGE: 'php'
    DOCKER_TAG: 'fpm-v8-mysqli'
    DOCKER_FILE: 'Dockerfile_php'
    DOCKER_BUILD_ARGS: '--build-arg PHP_IMAGE=8.2-fpm-alpine --build-arg DB_EXT=mysqli'
    PLATFORM: 'linux/amd64,linux/arm64/v8'
  when: manual