include:
  - project: 'jet-studio-io/gitlab-template'
    ref: 'latest'
    file: 'gitlab-ci-template.yml'

stages:
  - 📦 Build Image
  - 📦 Production Image

Gitlab CI:
  extends: .build-base
  stage: 📦 Build Image
  variables:
    DOCKER_IMAGE: 'jetx'
    DOCKER_TAG: 'gitlab-ci'
    DOCKER_FILE: 'Dockerfile_ci'
    DOCKER_BUILD_ARGS: '--build-arg PRODUCTION_IP=$PRODUCTION_IP --build-arg STAGING_IP=$STAGING_IP'
  when: manual

PHP cli:
  extends: .build-base
  stage: 📦 Build Image
  variables:
    DOCKER_IMAGE: 'php'
    DOCKER_TAG: 'cli-v8'
    DOCKER_FILE: 'Dockerfile_php'
    DOCKER_BUILD_ARGS: '--build-arg PHP_IMAGE=8.2-cli-alpine'
  when: manual

PHP fpm pg:
  extends: .build-base
  stage: 📦 Production Image
  variables:
    DOCKER_IMAGE: 'php'
    DOCKER_TAG: 'fpm-v8-pg'
    DOCKER_FILE: 'Dockerfile_php'
    DOCKER_BUILD_ARGS: '--build-arg PHP_IMAGE=8.2-fpm-alpine'
    PLATFORM: 'linux/amd64,linux/arm64/v8'
    DB_EXT: 'pdo pdo_pgsql'
    DB_EXT_LIB: 'postgresql-dev'
  when: manual

PHP fpm mysql:
  extends: .build-base
  stage: 📦 Production Image
  variables:
    DOCKER_IMAGE: 'php'
    DOCKER_TAG: 'fpm-v8-pdo'
    DOCKER_FILE: 'Dockerfile_php'
    DOCKER_BUILD_ARGS: '--build-arg PHP_IMAGE=8.2-fpm-alpine'
    PLATFORM: 'linux/amd64,linux/arm64/v8'
    DB_EXT: 'pdo pdo_mysql'
    DB_EXT_LIB: ''
  when: manual

# Install mysqli for wordpress project
PHP fpm mysqli:
  extends: .build-base
  stage: 📦 Production Image
  variables:
    DOCKER_IMAGE: 'php'
    DOCKER_TAG: 'fpm-v8-mysqli'
    DOCKER_FILE: 'Dockerfile_php'
    DOCKER_BUILD_ARGS: '--build-arg PHP_IMAGE=8.2-fpm-alpine'
    PLATFORM: 'linux/amd64,linux/arm64/v8'
    DB_EXT: 'mysqli'
    DB_EXT_LIB: ''
  when: manual