include:
  - project: 'jet-studio-io/gitlab-template'
    ref: 'latest'
    file: 'gitlab-ci-template.yml'

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - 📦 Build Image

Gitlab CI:
  extends: .build-base
  stage: 📦 Build Image
  variables:
    DOCKER_IMAGE: 'jetx'
    DOCKER_TAG: 'gitlab-ci'
    DOCKER_FILE: 'Dockerfile_ci'
    DOCKER_BUILD_ARGS: '--build-arg PRODUCTION_IP=$PRODUCTION_IP --build-arg STAGING_IP=$STAGING_IP'
  when: manual

PHP cli:
  extends: .build-base
  stage: 📦 Build Image
  variables:
    DOCKER_IMAGE: 'php'
    DOCKER_TAG: 'cli-v8'
    DOCKER_FILE: 'Dockerfile_php'
    DOCKER_BUILD_ARGS: '--build-arg PHP_IMAGE=8.2-cli-alpine'
  when: manual

PHP fpm:
  extends: .build-base
  stage: 📦 Build Image
  variables:
    DOCKER_IMAGE: 'php'
    DOCKER_TAG: 'fpm-v8'
    DOCKER_FILE: 'Dockerfile_php'
    DOCKER_BUILD_ARGS: '--build-arg PHP_IMAGE=8.2-fpm-alpine3.16'
    PLATFORM: 'linux/arm64/v8'
  when: manual