ARG PHP_IMAGE
FROM composer:2.3.7 AS composer
FROM php:$PHP_IMAGE

COPY --from=composer /usr/bin/composer /usr/bin/composer

####### Install essential tool #########
RUN set -eux
RUN apk add --update git bash gettext
## Install build tool & PHP extension ###
RUN apk add --update --no-cache \
	$PHPIZE_DEPS icu-dev libssh2-dev libxml2-dev zlib-dev libzip-dev zip jpeg-dev libpng-dev linux-headers

RUN	docker-php-ext-configure zip
RUN	docker-php-ext-configure gd --with-jpeg
RUN	docker-php-ext-install -j$(nproc) intl zip calendar pdo pdo_mysql bcmath exif gd
RUN	pecl install apcu
RUN	pecl clear-cache
RUN	docker-php-ext-enable apcu opcache

######## Config PHP ###########
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
COPY jetx.ini /usr/local/etc/php/conf.d/jetx.ini

EXPOSE 9000