FROM docker:cli

RUN apk add openssh-client git

# Create production docker engine context
ARG PRODUCTION_IP
RUN docker context create \
    --docker host=ssh://jetxdev@${PRODUCTION_IP} \
    --description="Production engine" \
    production-engine

# Create staging docker engine context
ARG STAGING_IP
RUN docker context create \
    --docker host=ssh://jetxdev@${STAGING_IP} \
    --description="Staging engine" \
    staging-engine