ARG PHP_IMAGE
FROM composer:2.3.7 AS composer
FROM php:$PHP_IMAGE

COPY --from=composer /usr/bin/composer /usr/bin/composer

####### Install essential tool #########
RUN set -eux
RUN apk add --update git bash gettext
## Install build tool & PHP extension ###
RUN apk add --update --no-cache --virtual .build-deps \
	$PHPIZE_DEPS icu-dev libssh2-dev libxml2-dev zlib-dev libzip-dev zip jpeg-dev libpng-dev linux-headers && \
	docker-php-ext-configure zip && \
	docker-php-ext-configure gd --with-jpeg && \
	docker-php-ext-install -j$(nproc) intl zip calendar pdo pdo_mysql bcmath exif gd && \
	pecl install apcu && \
	pecl clear-cache && \
	docker-php-ext-enable apcu opcache && \
	runDeps="$( \
		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
		| tr ',' '\n' \
		| sort -u \
		| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
	)" && \
	apk add --no-cache --virtual .api-phpexts-rundeps $runDeps && \
	apk del .build-deps

######## Config PHP ###########
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
COPY jetx.ini /usr/local/etc/php/conf.d/jetx.ini

EXPOSE 9000